spring:
  application:
    name: springboot-dubbo-user
  datasource:
    url: jdbc:mysql://10.98.17.4:3306/fengjiandb
    username: fengjian
    password: fengjian
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.fengjian.user.business.pojo

dubbo:
  application:
    id: springboot-dubbo-user-provider
    name: springboot-dubbo-user-provider
    qos-port: 22222
    qos-enable: true
  protocol:
    id: dubbo
    name: dubbo
    port: 20881
    status: server
  registry:
    id: zookeeper
    protocol: zookeeper
    address:  127.0.0.1:2181
  provider:
    filter: user-log-filter
    version: 1.0.0
    timeout: 60000
  scan:
    basePackages: com.fengjian

#####日志配置#####
logging:
  config: classpath:log4j2.xml

#=====================================
#自定义配置数据

#####日志脱敏配置#####
log4jConfig:
  encodeCharKeys: retCode,retMsg

